//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelodiasDelMundo_Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeDataContract", Namespace="http://schemas.datacontract.org/2004/07/MelodiasService")]
    [System.SerializableAttribute()]
    public partial class EmployeeDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int phone {
            get {
                return this.phoneField;
            }
            set {
                if ((this.phoneField.Equals(value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surnames {
            get {
                return this.surnamesField;
            }
            set {
                if ((object.ReferenceEquals(this.surnamesField, value) != true)) {
                    this.surnamesField = value;
                    this.RaisePropertyChanged("surnames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.zipCodeField, value) != true)) {
                    this.zipCodeField = value;
                    this.RaisePropertyChanged("zipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDataContract", Namespace="http://schemas.datacontract.org/2004/07/MelodiasService")]
    [System.SerializableAttribute()]
    public partial class ProductDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasSalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PurchasePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasSales {
            get {
                return this.HasSalesField;
            }
            set {
                if ((this.HasSalesField.Equals(value) != true)) {
                    this.HasSalesField = value;
                    this.RaisePropertyChanged("HasSales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PurchasePrice {
            get {
                return this.PurchasePriceField;
            }
            set {
                if ((this.PurchasePriceField.Equals(value) != true)) {
                    this.PurchasePriceField = value;
                    this.RaisePropertyChanged("PurchasePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalePrice {
            get {
                return this.SalePriceField;
            }
            set {
                if ((this.SalePriceField.Equals(value) != true)) {
                    this.SalePriceField = value;
                    this.RaisePropertyChanged("SalePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierDTO", Namespace="http://schemas.datacontract.org/2004/07/MelodiasService.DTOs")]
    [System.SerializableAttribute()]
    public partial class SupplierDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupplierIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((this.SupplierIdField.Equals(value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaleDataContract", Namespace="http://schemas.datacontract.org/2004/07/MelodiasService")]
    [System.SerializableAttribute()]
    public partial class SaleDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCancelledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SaleDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MelodiasDelMundo_Client.ServiceReference1.SaleDetailDataContract[] SaleDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SaleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCancelled {
            get {
                return this.IsCancelledField;
            }
            set {
                if ((this.IsCancelledField.Equals(value) != true)) {
                    this.IsCancelledField = value;
                    this.RaisePropertyChanged("IsCancelled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SaleDate {
            get {
                return this.SaleDateField;
            }
            set {
                if ((this.SaleDateField.Equals(value) != true)) {
                    this.SaleDateField = value;
                    this.RaisePropertyChanged("SaleDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MelodiasDelMundo_Client.ServiceReference1.SaleDetailDataContract[] SaleDetails {
            get {
                return this.SaleDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.SaleDetailsField, value) != true)) {
                    this.SaleDetailsField = value;
                    this.RaisePropertyChanged("SaleDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SaleId {
            get {
                return this.SaleIdField;
            }
            set {
                if ((this.SaleIdField.Equals(value) != true)) {
                    this.SaleIdField = value;
                    this.RaisePropertyChanged("SaleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUsersManager")]
    public interface IUsersManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/LogIn", ReplyAction="http://tempuri.org/IUsersManager/LogInResponse")]
        bool LogIn(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/LogIn", ReplyAction="http://tempuri.org/IUsersManager/LogInResponse")]
        System.Threading.Tasks.Task<bool> LogInAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/AddEmployee", ReplyAction="http://tempuri.org/IUsersManager/AddEmployeeResponse")]
        bool AddEmployee(MelodiasDelMundo_Client.ServiceReference1.EmployeeDataContract employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/AddEmployee", ReplyAction="http://tempuri.org/IUsersManager/AddEmployeeResponse")]
        System.Threading.Tasks.Task<bool> AddEmployeeAsync(MelodiasDelMundo_Client.ServiceReference1.EmployeeDataContract employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/DeleteEmployee", ReplyAction="http://tempuri.org/IUsersManager/DeleteEmployeeResponse")]
        bool DeleteEmployee(int idEmployee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/DeleteEmployee", ReplyAction="http://tempuri.org/IUsersManager/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(int idEmployee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/GetIdEmployeeByUserName", ReplyAction="http://tempuri.org/IUsersManager/GetIdEmployeeByUserNameResponse")]
        int GetIdEmployeeByUserName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/GetIdEmployeeByUserName", ReplyAction="http://tempuri.org/IUsersManager/GetIdEmployeeByUserNameResponse")]
        System.Threading.Tasks.Task<int> GetIdEmployeeByUserNameAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/UserNameExist", ReplyAction="http://tempuri.org/IUsersManager/UserNameExistResponse")]
        bool UserNameExist(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/UserNameExist", ReplyAction="http://tempuri.org/IUsersManager/UserNameExistResponse")]
        System.Threading.Tasks.Task<bool> UserNameExistAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/MailAlreadyExist", ReplyAction="http://tempuri.org/IUsersManager/MailAlreadyExistResponse")]
        bool MailAlreadyExist(string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/MailAlreadyExist", ReplyAction="http://tempuri.org/IUsersManager/MailAlreadyExistResponse")]
        System.Threading.Tasks.Task<bool> MailAlreadyExistAsync(string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/PhoneNumberExists", ReplyAction="http://tempuri.org/IUsersManager/PhoneNumberExistsResponse")]
        bool PhoneNumberExists(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/PhoneNumberExists", ReplyAction="http://tempuri.org/IUsersManager/PhoneNumberExistsResponse")]
        System.Threading.Tasks.Task<bool> PhoneNumberExistsAsync(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/GetEmployeeDetailsWithoutPassword", ReplyAction="http://tempuri.org/IUsersManager/GetEmployeeDetailsWithoutPasswordResponse")]
        MelodiasDelMundo_Client.ServiceReference1.EmployeeDataContract GetEmployeeDetailsWithoutPassword(int idEmployee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/GetEmployeeDetailsWithoutPassword", ReplyAction="http://tempuri.org/IUsersManager/GetEmployeeDetailsWithoutPasswordResponse")]
        System.Threading.Tasks.Task<MelodiasDelMundo_Client.ServiceReference1.EmployeeDataContract> GetEmployeeDetailsWithoutPasswordAsync(int idEmployee);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsersManagerChannel : MelodiasDelMundo_Client.ServiceReference1.IUsersManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersManagerClient : System.ServiceModel.ClientBase<MelodiasDelMundo_Client.ServiceReference1.IUsersManager>, MelodiasDelMundo_Client.ServiceReference1.IUsersManager {
        
        public UsersManagerClient() {
        }
        
        public UsersManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool LogIn(string username, string password) {
            return base.Channel.LogIn(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LogInAsync(string username, string password) {
            return base.Channel.LogInAsync(username, password);
        }
        
        public bool AddEmployee(MelodiasDelMundo_Client.ServiceReference1.EmployeeDataContract employee) {
            return base.Channel.AddEmployee(employee);
        }
        
        public System.Threading.Tasks.Task<bool> AddEmployeeAsync(MelodiasDelMundo_Client.ServiceReference1.EmployeeDataContract employee) {
            return base.Channel.AddEmployeeAsync(employee);
        }
        
        public bool DeleteEmployee(int idEmployee) {
            return base.Channel.DeleteEmployee(idEmployee);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(int idEmployee) {
            return base.Channel.DeleteEmployeeAsync(idEmployee);
        }
        
        public int GetIdEmployeeByUserName(string userName) {
            return base.Channel.GetIdEmployeeByUserName(userName);
        }
        
        public System.Threading.Tasks.Task<int> GetIdEmployeeByUserNameAsync(string userName) {
            return base.Channel.GetIdEmployeeByUserNameAsync(userName);
        }
        
        public bool UserNameExist(string userName) {
            return base.Channel.UserNameExist(userName);
        }
        
        public System.Threading.Tasks.Task<bool> UserNameExistAsync(string userName) {
            return base.Channel.UserNameExistAsync(userName);
        }
        
        public bool MailAlreadyExist(string mail) {
            return base.Channel.MailAlreadyExist(mail);
        }
        
        public System.Threading.Tasks.Task<bool> MailAlreadyExistAsync(string mail) {
            return base.Channel.MailAlreadyExistAsync(mail);
        }
        
        public bool PhoneNumberExists(int number) {
            return base.Channel.PhoneNumberExists(number);
        }
        
        public System.Threading.Tasks.Task<bool> PhoneNumberExistsAsync(int number) {
            return base.Channel.PhoneNumberExistsAsync(number);
        }
        
        public MelodiasDelMundo_Client.ServiceReference1.EmployeeDataContract GetEmployeeDetailsWithoutPassword(int idEmployee) {
            return base.Channel.GetEmployeeDetailsWithoutPassword(idEmployee);
        }
        
        public System.Threading.Tasks.Task<MelodiasDelMundo_Client.ServiceReference1.EmployeeDataContract> GetEmployeeDetailsWithoutPasswordAsync(int idEmployee) {
            return base.Channel.GetEmployeeDetailsWithoutPasswordAsync(idEmployee);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IProductsManager")]
    public interface IProductsManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsManager/RegisterProduct", ReplyAction="http://tempuri.org/IProductsManager/RegisterProductResponse")]
        bool RegisterProduct(MelodiasDelMundo_Client.ServiceReference1.ProductDataContract product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsManager/RegisterProduct", ReplyAction="http://tempuri.org/IProductsManager/RegisterProductResponse")]
        System.Threading.Tasks.Task<bool> RegisterProductAsync(MelodiasDelMundo_Client.ServiceReference1.ProductDataContract product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsManager/GetProducts", ReplyAction="http://tempuri.org/IProductsManager/GetProductsResponse")]
        MelodiasDelMundo_Client.ServiceReference1.ProductDataContract[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsManager/GetProducts", ReplyAction="http://tempuri.org/IProductsManager/GetProductsResponse")]
        System.Threading.Tasks.Task<MelodiasDelMundo_Client.ServiceReference1.ProductDataContract[]> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsManager/GetProductsSearch", ReplyAction="http://tempuri.org/IProductsManager/GetProductsSearchResponse")]
        MelodiasDelMundo_Client.ServiceReference1.ProductDataContract[] GetProductsSearch(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsManager/GetProductsSearch", ReplyAction="http://tempuri.org/IProductsManager/GetProductsSearchResponse")]
        System.Threading.Tasks.Task<MelodiasDelMundo_Client.ServiceReference1.ProductDataContract[]> GetProductsSearchAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsManager/EditProduct", ReplyAction="http://tempuri.org/IProductsManager/EditProductResponse")]
        bool EditProduct(MelodiasDelMundo_Client.ServiceReference1.ProductDataContract product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsManager/EditProduct", ReplyAction="http://tempuri.org/IProductsManager/EditProductResponse")]
        System.Threading.Tasks.Task<bool> EditProductAsync(MelodiasDelMundo_Client.ServiceReference1.ProductDataContract product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsManager/ExistsProductByName", ReplyAction="http://tempuri.org/IProductsManager/ExistsProductByNameResponse")]
        bool ExistsProductByName(string productName, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsManager/ExistsProductByName", ReplyAction="http://tempuri.org/IProductsManager/ExistsProductByNameResponse")]
        System.Threading.Tasks.Task<bool> ExistsProductByNameAsync(string productName, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsManager/DeleteProduct", ReplyAction="http://tempuri.org/IProductsManager/DeleteProductResponse")]
        bool DeleteProduct(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsManager/DeleteProduct", ReplyAction="http://tempuri.org/IProductsManager/DeleteProductResponse")]
        System.Threading.Tasks.Task<bool> DeleteProductAsync(int productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductsManagerChannel : MelodiasDelMundo_Client.ServiceReference1.IProductsManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductsManagerClient : System.ServiceModel.ClientBase<MelodiasDelMundo_Client.ServiceReference1.IProductsManager>, MelodiasDelMundo_Client.ServiceReference1.IProductsManager {
        
        public ProductsManagerClient() {
        }
        
        public ProductsManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductsManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisterProduct(MelodiasDelMundo_Client.ServiceReference1.ProductDataContract product) {
            return base.Channel.RegisterProduct(product);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterProductAsync(MelodiasDelMundo_Client.ServiceReference1.ProductDataContract product) {
            return base.Channel.RegisterProductAsync(product);
        }
        
        public MelodiasDelMundo_Client.ServiceReference1.ProductDataContract[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<MelodiasDelMundo_Client.ServiceReference1.ProductDataContract[]> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public MelodiasDelMundo_Client.ServiceReference1.ProductDataContract[] GetProductsSearch(string search) {
            return base.Channel.GetProductsSearch(search);
        }
        
        public System.Threading.Tasks.Task<MelodiasDelMundo_Client.ServiceReference1.ProductDataContract[]> GetProductsSearchAsync(string search) {
            return base.Channel.GetProductsSearchAsync(search);
        }
        
        public bool EditProduct(MelodiasDelMundo_Client.ServiceReference1.ProductDataContract product) {
            return base.Channel.EditProduct(product);
        }
        
        public System.Threading.Tasks.Task<bool> EditProductAsync(MelodiasDelMundo_Client.ServiceReference1.ProductDataContract product) {
            return base.Channel.EditProductAsync(product);
        }
        
        public bool ExistsProductByName(string productName, int productId) {
            return base.Channel.ExistsProductByName(productName, productId);
        }
        
        public System.Threading.Tasks.Task<bool> ExistsProductByNameAsync(string productName, int productId) {
            return base.Channel.ExistsProductByNameAsync(productName, productId);
        }
        
        public bool DeleteProduct(int productId) {
            return base.Channel.DeleteProduct(productId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProductAsync(int productId) {
            return base.Channel.DeleteProductAsync(productId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISuppliersManager")]
    public interface ISuppliersManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliersManager/RegisterSupplier", ReplyAction="http://tempuri.org/ISuppliersManager/RegisterSupplierResponse")]
        bool RegisterSupplier(MelodiasDelMundo_Client.ServiceReference1.SupplierDTO supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliersManager/RegisterSupplier", ReplyAction="http://tempuri.org/ISuppliersManager/RegisterSupplierResponse")]
        System.Threading.Tasks.Task<bool> RegisterSupplierAsync(MelodiasDelMundo_Client.ServiceReference1.SupplierDTO supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliersManager/EditSupplier", ReplyAction="http://tempuri.org/ISuppliersManager/EditSupplierResponse")]
        bool EditSupplier(MelodiasDelMundo_Client.ServiceReference1.SupplierDTO supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliersManager/EditSupplier", ReplyAction="http://tempuri.org/ISuppliersManager/EditSupplierResponse")]
        System.Threading.Tasks.Task<bool> EditSupplierAsync(MelodiasDelMundo_Client.ServiceReference1.SupplierDTO supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliersManager/GetSuppliers", ReplyAction="http://tempuri.org/ISuppliersManager/GetSuppliersResponse")]
        MelodiasDelMundo_Client.ServiceReference1.SupplierDTO[] GetSuppliers(string searchCiteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliersManager/GetSuppliers", ReplyAction="http://tempuri.org/ISuppliersManager/GetSuppliersResponse")]
        System.Threading.Tasks.Task<MelodiasDelMundo_Client.ServiceReference1.SupplierDTO[]> GetSuppliersAsync(string searchCiteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliersManager/IsSupplierNameTaken", ReplyAction="http://tempuri.org/ISuppliersManager/IsSupplierNameTakenResponse")]
        bool IsSupplierNameTaken(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliersManager/IsSupplierNameTaken", ReplyAction="http://tempuri.org/ISuppliersManager/IsSupplierNameTakenResponse")]
        System.Threading.Tasks.Task<bool> IsSupplierNameTakenAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliersManager/IsSupplierEmailTaken", ReplyAction="http://tempuri.org/ISuppliersManager/IsSupplierEmailTakenResponse")]
        bool IsSupplierEmailTaken(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliersManager/IsSupplierEmailTaken", ReplyAction="http://tempuri.org/ISuppliersManager/IsSupplierEmailTakenResponse")]
        System.Threading.Tasks.Task<bool> IsSupplierEmailTakenAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliersManager/DeleteSupplier", ReplyAction="http://tempuri.org/ISuppliersManager/DeleteSupplierResponse")]
        bool DeleteSupplier(int supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliersManager/DeleteSupplier", ReplyAction="http://tempuri.org/ISuppliersManager/DeleteSupplierResponse")]
        System.Threading.Tasks.Task<bool> DeleteSupplierAsync(int supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliersManager/RegisterPurchase", ReplyAction="http://tempuri.org/ISuppliersManager/RegisterPurchaseResponse")]
        bool RegisterPurchase(MelodiasDelMundo_Client.ServiceReference1.PurchaseDTO purchase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliersManager/RegisterPurchase", ReplyAction="http://tempuri.org/ISuppliersManager/RegisterPurchaseResponse")]
        System.Threading.Tasks.Task<bool> RegisterPurchaseAsync(MelodiasDelMundo_Client.ServiceReference1.PurchaseDTO purchase);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISuppliersManagerChannel : MelodiasDelMundo_Client.ServiceReference1.ISuppliersManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SuppliersManagerClient : System.ServiceModel.ClientBase<MelodiasDelMundo_Client.ServiceReference1.ISuppliersManager>, MelodiasDelMundo_Client.ServiceReference1.ISuppliersManager {
        
        public SuppliersManagerClient() {
        }
        
        public SuppliersManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SuppliersManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuppliersManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuppliersManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisterSupplier(MelodiasDelMundo_Client.ServiceReference1.SupplierDTO supplier) {
            return base.Channel.RegisterSupplier(supplier);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterSupplierAsync(MelodiasDelMundo_Client.ServiceReference1.SupplierDTO supplier) {
            return base.Channel.RegisterSupplierAsync(supplier);
        }
        
        public bool EditSupplier(MelodiasDelMundo_Client.ServiceReference1.SupplierDTO supplier) {
            return base.Channel.EditSupplier(supplier);
        }
        
        public System.Threading.Tasks.Task<bool> EditSupplierAsync(MelodiasDelMundo_Client.ServiceReference1.SupplierDTO supplier) {
            return base.Channel.EditSupplierAsync(supplier);
        }
        
        public MelodiasDelMundo_Client.ServiceReference1.SupplierDTO[] GetSuppliers(string searchCiteria) {
            return base.Channel.GetSuppliers(searchCiteria);
        }
        
        public System.Threading.Tasks.Task<MelodiasDelMundo_Client.ServiceReference1.SupplierDTO[]> GetSuppliersAsync(string searchCiteria) {
            return base.Channel.GetSuppliersAsync(searchCiteria);
        }
        
        public bool IsSupplierNameTaken(string name) {
            return base.Channel.IsSupplierNameTaken(name);
        }
        
        public System.Threading.Tasks.Task<bool> IsSupplierNameTakenAsync(string name) {
            return base.Channel.IsSupplierNameTakenAsync(name);
        }
        
        public bool IsSupplierEmailTaken(string email) {
            return base.Channel.IsSupplierEmailTaken(email);
        }
        
        public System.Threading.Tasks.Task<bool> IsSupplierEmailTakenAsync(string email) {
            return base.Channel.IsSupplierEmailTakenAsync(email);
        }
        
        public bool DeleteSupplier(int supplierId) {
            return base.Channel.DeleteSupplier(supplierId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSupplierAsync(int supplierId) {
            return base.Channel.DeleteSupplierAsync(supplierId);
        }
        
        public bool RegisterPurchase(MelodiasDelMundo_Client.ServiceReference1.PurchaseDTO purchase) {
            return base.Channel.RegisterPurchase(purchase);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterPurchaseAsync(MelodiasDelMundo_Client.ServiceReference1.PurchaseDTO purchase) {
            return base.Channel.RegisterPurchaseAsync(purchase);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISalesManager")]
    public interface ISalesManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManager/GetSales", ReplyAction="http://tempuri.org/ISalesManager/GetSalesResponse")]
        MelodiasDelMundo_Client.ServiceReference1.SaleDataContract[] GetSales(string customerName, System.Nullable<System.DateTime> date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManager/GetSales", ReplyAction="http://tempuri.org/ISalesManager/GetSalesResponse")]
        System.Threading.Tasks.Task<MelodiasDelMundo_Client.ServiceReference1.SaleDataContract[]> GetSalesAsync(string customerName, System.Nullable<System.DateTime> date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManager/RegisterSale", ReplyAction="http://tempuri.org/ISalesManager/RegisterSaleResponse")]
        bool RegisterSale(MelodiasDelMundo_Client.ServiceReference1.SaleDataContract sale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManager/RegisterSale", ReplyAction="http://tempuri.org/ISalesManager/RegisterSaleResponse")]
        System.Threading.Tasks.Task<bool> RegisterSaleAsync(MelodiasDelMundo_Client.ServiceReference1.SaleDataContract sale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManager/EditSale", ReplyAction="http://tempuri.org/ISalesManager/EditSaleResponse")]
        bool EditSale(MelodiasDelMundo_Client.ServiceReference1.SaleDataContract sale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManager/EditSale", ReplyAction="http://tempuri.org/ISalesManager/EditSaleResponse")]
        System.Threading.Tasks.Task<bool> EditSaleAsync(MelodiasDelMundo_Client.ServiceReference1.SaleDataContract sale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManager/CancelSale", ReplyAction="http://tempuri.org/ISalesManager/CancelSaleResponse")]
        bool CancelSale(int saleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManager/CancelSale", ReplyAction="http://tempuri.org/ISalesManager/CancelSaleResponse")]
        System.Threading.Tasks.Task<bool> CancelSaleAsync(int saleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManager/GetSaleById", ReplyAction="http://tempuri.org/ISalesManager/GetSaleByIdResponse")]
        MelodiasDelMundo_Client.ServiceReference1.SaleDataContract GetSaleById(int saleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManager/GetSaleById", ReplyAction="http://tempuri.org/ISalesManager/GetSaleByIdResponse")]
        System.Threading.Tasks.Task<MelodiasDelMundo_Client.ServiceReference1.SaleDataContract> GetSaleByIdAsync(int saleId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalesManagerChannel : MelodiasDelMundo_Client.ServiceReference1.ISalesManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesManagerClient : System.ServiceModel.ClientBase<MelodiasDelMundo_Client.ServiceReference1.ISalesManager>, MelodiasDelMundo_Client.ServiceReference1.ISalesManager {
        
        public SalesManagerClient() {
        }
        
        public SalesManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MelodiasDelMundo_Client.ServiceReference1.SaleDataContract[] GetSales(string customerName, System.Nullable<System.DateTime> date) {
            return base.Channel.GetSales(customerName, date);
        }
        
        public System.Threading.Tasks.Task<MelodiasDelMundo_Client.ServiceReference1.SaleDataContract[]> GetSalesAsync(string customerName, System.Nullable<System.DateTime> date) {
            return base.Channel.GetSalesAsync(customerName, date);
        }
        
        public bool RegisterSale(MelodiasDelMundo_Client.ServiceReference1.SaleDataContract sale) {
            return base.Channel.RegisterSale(sale);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterSaleAsync(MelodiasDelMundo_Client.ServiceReference1.SaleDataContract sale) {
            return base.Channel.RegisterSaleAsync(sale);
        }
        
        public bool EditSale(MelodiasDelMundo_Client.ServiceReference1.SaleDataContract sale) {
            return base.Channel.EditSale(sale);
        }
        
        public System.Threading.Tasks.Task<bool> EditSaleAsync(MelodiasDelMundo_Client.ServiceReference1.SaleDataContract sale) {
            return base.Channel.EditSaleAsync(sale);
        }
        
        public bool CancelSale(int saleId) {
            return base.Channel.CancelSale(saleId);
        }
        
        public System.Threading.Tasks.Task<bool> CancelSaleAsync(int saleId) {
            return base.Channel.CancelSaleAsync(saleId);
        }
        
        public MelodiasDelMundo_Client.ServiceReference1.SaleDataContract GetSaleById(int saleId) {
            return base.Channel.GetSaleById(saleId);
        }
        
        public System.Threading.Tasks.Task<MelodiasDelMundo_Client.ServiceReference1.SaleDataContract> GetSaleByIdAsync(int saleId) {
            return base.Channel.GetSaleByIdAsync(saleId);
        }
    }
}
